### ISSUE TITLE
Break of libpar2 >= 0.8.0 

### ISSUE THREAD

**Issue by zvezdochiot** [vividnightmare/gpar2#1]
**libpar2 >= 0.8.0**: https://github.com/Parchive/par2cmdline

Not head:
https://github.com/vividnightmare/gpar2/blob/ba99d4ddbd7e0fc6447c69a6b530f03902723065/gpar2.h#L13

Not declared in `/usr/include/libpar2`:
```make
mainwindow.h:61:23: error: ‘ParHeaders’ has not been declared
mainwindow.h:66:3: error: ‘LibPar2’ does not name a type
```

**Comment by vividnightmare** [comment]
https://github.com/vividnightmare/libpar2

**Comment by zvezdochiot** [comment]
https://github.com/vividnightmare/libpar2/releases/tag/0.2

( released this on 22 Feb 2017)

Version 0.2? Seriously?

**Comment by vividnightmare** [comment]
As far as I'm aware, this is the most recent version of libpar2 in existence.
https://github.com/Parchive/libpar2/blob/master/ChangeLog

**Comment by zvezdochiot** [comment]
https://github.com/Parchive/par2cmdline/releases/tag/v0.8.1

(released this 2 hours ago)

https://github.com/Parchive/par2cmdline/blob/master/ChangeLog

**Comment by vividnightmare** [comment]
libpar2 != par2cmdline

If you want to update libpar2, patches are welcome, but I would suggest discussing that in https://github.com/Parchive/libpar2 as this would probably be considered upstream.

It's old software and for about 10 years upstream was dead, which is why I have my own copies here.

**Comment by zvezdochiot** [comment]
libpar2 (0.2) == par2cmdline (rel-0-4)

https://github.com/vividnightmare/libpar2/releases/tag/0.2 ==  https://github.com/Parchive/par2cmdline/releases/tag/rel-0-4

**Comment by vividnightmare** [comment]
Do you have a question?

**Comment by zvezdochiot** [comment]
I need time to produce a full-blown diff. Then there will be a question.
